### PR TITLE
Refinements for Confluence

### PR DESCRIPTION
**Pull request by aheusingfeld**
Added some conversion in respect to #9
- extracted all asciidoc specific conversion into the "parseBody()" function
- added conversion of code blocks to code macro
- added conversion for admonitions TIP, CAUTION, NOTE, WARNING and IMPORTANT including their title into Confluence macro
- removed unnecessary wrapping divs (.paragraph, .ulist, .sect3, .listingblock, .title) as these cause Confluence to omit the margin between the paragraphs
- upgraded JSoup from 1.7.3 to 1.8.2

### CODE REVIEW

**Comment by rdmueller** [comment]
Thanx for the contribution! I'll add my code to the toc in just a minute - I think #9 will then be ready to be closed...

**Comment by rdmueller** [comment]
hm. something went wrong - at least for me...

can't get it to work anymore. With a slight change of the code, the master page will be created but for the next one I get the following error:

something went wrong - got an https response code 400:
[data:[authorized:false, errors:[], valid:true], message:Error parsing xhtml, statusCode:400]

Does it work for you?

**Comment by aheusingfeld** [comment]
Oh, I forgot to check the "confluenceCreateSubpages = true" tests. Sorry. Will check later today

**Comment by rdmueller** [comment]
found the problem... was really hard to find:

the new version outputs html, not xhtml => `<hr>!=<hr />`
This leads to the exception above. will open a new issue...

**Comment by rdmueller** [comment]
just commited some fixes - subpages work, updates work and xhtml partly works...

**Pull request merged**
