### PR TITLE
Suggestions for optimization

### PR DESCRIPTION
**Pull request by aheusingfeld**
## Configuration
- added `confluenceCreateSubpages` parameter to be able to switch off creation of subpages
- changed `input` parameter into a list of files
- one can now also configure a parent page by file
## asciidoc2confluence
- adopted new config parameters
- added more log output
- added check whether 'ancestorId' is provided, if not a new master page will be created
## README
- switched from Markdown to Asciidoc
- added section about usage with Maven and GMavenPlus
## FIXME
- added the `scriptBasePath` variable which now MUST be set as otherwise the `asciidoc2confluence.groovy` will not be able to find the `Config.groovy` file. Couldn't find a better way to retrieve the path to the Config.groovy file. Suggestions and optimizations are very welcome!

### CODE REVIEW

**Comment by rdmueller** [comment]
Wow. Thanx for the rebase...!

**Comment by aheusingfeld** [comment]
Thanks for all your effort on the script, it works like a charm. I see 2 more tasks to make the script even more convenient to use
1. Think about proper packaging + versioning so that people can include the script as a dependency into their build
2. (will come in as we discuss 1.): Once we have a package, we need to find a better way to handle the configuration

Maybe @gernotstarke or @mojavelinux have more input on this.

**Comment by mojavelinux** [comment]
I love the idea of this script, though I wonder if it would be possible to align efforts with https://github.com/asciidoctor/asciidoctor-confluence. More ideas on where we are headed with this script are outlined in the following post: http://discuss.asciidoctor.org/Asciidoctor-CMS-publisher-td3022.html

cc: @gscheibel

**Comment by rdmueller** [comment]
@mojavelinux : Good Idea! When I started with this script I wasn't aware of the asciidoctor-confluence plugin, but I have no problem to drop this project for an equal asciidoctor plugin. Let's see - my ruby knowledge is limited at the moment... created issue #5 to align efforts

**Comment by mojavelinux** [comment]
:+1: 

If you know Groovy, you know Ruby...it really is very similar. That's basically how I figured it out.

**Pull request merged**
